#!/bin/sh
# ./create_kwame

# Method n. 1

FILE=\"\\\?\$\*\'KwaMe\'\*\$\?\\\"

echo -n 42 > "\"\?\$*'KwaMe'*\$?\\\""
# Create file and add 42
chmod 614 $FILE
# Change permissions
touch -t 10021221 $FILE
# Change time
ls -lRa *waM* | cat -e
# Check file

# You don't have to push this !
