#!/bin/sh
# ./comb_test

gcc -Wall -Wextra -Werror ft_print_comb.c main.c
# Compile the source code
./a.out | tr " " "\n" | sed 's/,//g' > comb_list
# Execute and redirect the output
echo >> comb_list && wc -l comb_list | awk '{print $1}'
# Add a new line and count the total lines
rm a.out comb_list
# Clean the current directory

# Target: if the number matches the C(n, k) the game is done.

# You don't have to push this !
