#!/bin/sh
# ./patch

tar -xf resources.tar.gz
# Extract compress folder
patch a -i sw.diff -o b 
# To obtain b you to have apply sw.diff to a
rm a sw.diff ._*
# Remove extracted files

# You don't have to push this !
